### ISSUE TITLE
Thumbnail 64Bit issue

### ISSUE THREAD

**Issue by radzimir** [cabbagecreek/Marlin3DprinterTool#143]
Hi, 

I got an error on my Windows 10 64Bit maschine while installing Thumbnail Shell Extension.

![stl_thumbnail_shell_extension_64bit_error](https://user-images.githubusercontent.com/12893394/30756768-4e14fdc2-9fcc-11e7-93c2-8a3152ca191c.PNG)

**Comment by cabbagecreek** [comment]
Ununstall the program and download from this link
http://marlin3dprintertool.se/LatestVersion/Marlin3DprinterTool.msi

If this dont work contact me at  c a b b a g e c r e e k ( a ) g m a i l . c o m and I will try to solve the problem thru TeamViewer and/or Skype

**Comment by cabbagecreek** [comment]
This problem is solved in #147. The new 0.24-beta should handle this problem. The new 0.24-beta should be auto-apdated .. Look at previous comment if the Auto-update is not working.

Sometimes the STL thumbnail Provider file is locked in C:\program x86\Marlin3dPrinterTool directory. 
Unregister the STL thumbnail Provider in Marlin3DprinterToolSTLconfig and reboot. 
Now the STL thumbnail Provider DLL is possible to overwrite. Rerun the install /repair and the DLL will be overwritten

Closing this issue because it is solved in #147
